### ISSUE TITLE
你好，请问fps能达到多少

### ISSUE THREAD

**Issue by courtfu** [yatengLG/SSD-Pytorch#1]

**Comment by yatengLG** [comment]
2080ti ,单张图片 5目标, 前向传播用时14.16ms, 使用score进行分数抑制后 差不多 14.32ms. 具体的整体没统计过.

**Comment by yatengLG** [comment]
就项目说明中的那张图,2目标, 2080ti下, 总体15.13ms.

**Comment by crystalcici** [comment]
你好，请问你是用的torch1.2的版本吗

**Comment by yatengLG** [comment]
这个我也忘了,对pytorch我记得没有要求0.4以上吧. 不过需要torchvision 0.3.0 以上.
