### ISSUE TITLE
"Invalid device id"

### ISSUE THREAD

**Issue by KeepFaithMe** [yatengLG/SSD-Pytorch#10]
尊敬的开发者：
     您好
     在将您的代码下载下来，环境配置正确之后，在run train_demo.py时，出现‘AssertionError: Invalid device id’这样的错误，请问我应该如何设置呢？这个错误是由于我的GUP设置不对吗？希望您能给我一点介意，刚入门深度学习，谢谢您！
    祝好！

**Comment by yatengLG** [comment]
你可以查看Configs.py文件，里面各参数有具体的注释。

你当前的问题，是由于指定的GPU id 错误。你可以把 Configs.py 中 

_C.DEVICE.TRAIN_DEVICES = [0,1] # 训练gpu
_C.DEVICE.TEST_DEVICES = [0,1]  # 检测gpu

均改为  [0]即可解决。
