### ISSUE TITLE
center_form_to_corner_form 

### ISSUE THREAD

**Issue by KeepFaithMe** [yatengLG/SSD-Pytorch#11]
尊敬的开发者：
     您好！
     看了你的代码，收益很多，但是其中有一些不明白的地方一直困扰着我，在您的代码中（Boxs_op.py文件）有这样一个方法：center_form_to_corner_form(locations),根据您的注释‘[x, y, w, h] to [xmin, ymin, xmax, ymax]’，在这里我有个不明白的地方，第一：为什么要做这一步操作呢？第二：在做这一步时，你的具体算法根据我的理解是：[x,y] -[w,h] /2 为xmin和ymin，[x,y]+[w,h]/2为xmax，ymax，为什么不直接是[x,y]即为xmin,ymin,[x,y]+[w,h]为xmax,ymax?您的做法最终会导致出现xy负数，因此您还要做clamp_(max=1,min=0)这个操作，而如果像后者那样的话就不需要做这一步？此外，您在后面还做了一步逆向操作，为什么呢？这一部分我非常的困惑，希望耽搁您一点宝贵的时间，解开我的疑惑。我正在入门深度学习目标检测这一块，很多知识面都是空缺，所以希望依靠您的代码，一点一点的把空缺填补起来，谢谢您！
   祝好！

**Comment by yatengLG** [comment]
很高兴能帮助到你！
采用[x, y, w, h]的形式，主要与损失函数的计算有关。对于框体，在计算损失时，采用预测框与检测框 中心的偏移量，和宽高的偏移量作为框体回归的损失。 所以，需要使用，xy来表示检测框的中心，使用wh来表示检测框的宽高，来确定一个检测框。

但是这种形式，在处理边界时，你的检测框覆盖面就会出现超出图片的现象，而标注框肯定是没有超出图片的，这样会对处于边界的目标的损失造成影响，所以需要对超出图片的检测框进行截断。也就是你所说的clamp_(max=1,min=0)操作。

这里xy是检测框的中心，而 xmin,ymin,xmax,ymax是左上角和右下角。只是表示方式不同而已。 你如果喜欢使用 xmin,ymin,xmax,ymax的方式也是可以的。  但是你在生成检测框时，就会变得很复杂，且不易检测生成的检测框是否正确。检测框生成部分可以自己看代码 Model/structs/Anchors.py部分。

如果对你有所帮助，欢迎star和fork。

**Comment by KeepFaithMe** [comment]
非常感谢您的回复，我大概明白了您的意思！谢谢您！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yatengLG/SSD-Pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 下午5:37
收件人:&nbsp;"yatengLG/SSD-Pytorch"<SSD-Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"张川"<1071244263@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yatengLG/SSD-Pytorch] center_form_to_corner_form  (#11)





 
很高兴能帮助到你！
 采用[x, y, w, h]的形式，主要与损失函数的计算有关。对于框体，在计算损失时，采用预测框与检测框 中心的偏移量，和宽高的偏移量作为框体回归的损失。 所以，需要使用，xy来表示检测框的中心，使用wh来表示检测框的宽高，来确定一个检测框。
 
但是这种形式，在处理边界时，你的检测框覆盖面就会出现超出图片的现象，而标注框肯定是没有超出图片的，这样会对处于边界的目标的损失造成影响，所以需要对超出图片的检测框进行截断。也就是你所说的clamp_(max=1,min=0)操作。
 
这里xy是检测框的中心，而 xmin,ymin,xmax,ymax是左上角和右下角。只是表示方式不同而已。 你如果喜欢使用 xmin,ymin,xmax,ymax的方式也是可以的。  但是你在生成检测框时，就会变得很负责，且不易检测生成的检测框是否正确。检测框生成部分可以自己看代码 Model/structs/Anchors.py部分。
 
如果对你有所帮助，欢迎star和fork。
