### ISSUE TITLE
参数问题

### ISSUE THREAD

**Issue by KeepFaithMe** [yatengLG/SSD-Pytorch#15]
博主您好！
     您的SSD实现代码非常棒，想通过您的代码，作为我入门目标检测的必备资料。关于您的SSD代码，有两个参数不理解其作用，希望能占用您一点时间，替我解答一下。 
     _C.MODEL.ANCHORS.CENTER_VARIANCE = 0.1  # 解码
      _C.MODEL.ANCHORS.SIZE_VARIANCE = 0.2    # 解码
     我不明白这两个参数的意义何在？这个问题困扰了我很久。
另外，关于下面这两个参数：
_C.MODEL.INPUT.PIXEL_MEAN = [0, 0, 0] #数据集均值
_C.MODEL.INPUT.PIXEL_STD = [1, 1, 1] # 数据集方差
如果我没猜错的话，应该是对整个数据集求其均值与方差。
期待您的回复！
祝您身体健康，工作顺利！

**Comment by yatengLG** [comment]
CENTER_VARIANCE， SIZE_VARIANCE 在代码中的应用在编码和解码这两个部分。
https://github.com/yatengLG/SSD-Pytorch/blob/cdf7076b2d4fee388d90c53c6acd31813a4a7c46/Utils/Boxs_op.py#L34

理解编码和解码的作用，就比较好理解这个参数了。
编码的输入，是标注框与检测框(anchor，代码中是prior)，以及这两个参数，  然后编码的结果拿去计算损失。
编码的输出，分别是中心偏移，以及尺寸差异。 对中心偏移和尺寸差异 分别除以这两个参数，实际上的作用，就是对中心和尺寸的损失贡献做一个平衡。

像这里，中心偏移/0.1， 尺寸差异/0.2 ，意味着相对于尺寸，更加关注预测结果的中心。

至于 PIXEL_MEAN， PIXEL_STD 就是你说的整个数据集的均值和方差。

欢迎关注，有什么问题可以随时问我

**Comment by yatengLG** [comment]
控制中心落点和尺寸的损失影响，其实可以在损失函数中更加简便的实现。
但SSD原文是这么实现的

**Comment by KeepFaithMe** [comment]
CENTER_VARIANCE， SIZE_VARIANC这两个参数受什么的影响呢？是输入图片的尺寸，还是说与数据集中目标的大小？还是其它什么因素？

**Comment by yatengLG** [comment]
如果CENTER_VARIANCE 比SIZE_VARIANC小，则 中心偏移对损失的影响较大； 反之，则预测框尺寸随损失影响较大。

看你最终更加侧重哪方面。  

对这个参数的理解，类似于torch.nn.cross_entropy()中的weights参数

**Comment by KeepFaithMe** [comment]
好的，谢谢你的解释！非常感谢您！
