### ISSUE TITLE
希望训练支持CPU训练 照顾照顾 没有显卡的弟弟们

### ISSUE THREAD

**Issue by 72min** [yatengLG/SSD-Pytorch#16]

**Comment by yatengLG** [comment]
没gpu，训练不了，太慢了（令人发指的慢）。

如果你实在想试的话，可以改下面这部分：
https://github.com/yatengLG/SSD-Pytorch/blob/cdf7076b2d4fee388d90c53c6acd31813a4a7c46/Model/trainer.py#L90
https://github.com/yatengLG/SSD-Pytorch/blob/cdf7076b2d4fee388d90c53c6acd31813a4a7c46/Model/trainer.py#L117
去掉这两部分就可以了
