### ISSUE TITLE
求数据集来源

### ISSUE THREAD

**Issue by jxz2021114** [yatengLG/SSD-Pytorch#6]
请问大神，报错“ No such file or directory: '/home/XXX/VOCdevkit/VOC2007\\ImageSets\\Main\\train.txt'”，是因为需要制作自己的数据集再换成自己的路径吗？现在网络上是否有现成的数据集呢？

**Comment by yatengLG** [comment]
你去下载Pascal VOC 数据集即可。
如果需要训练自己的数据，把数据转成VOC格式(网上有很多文章和代码)即可使用原代码训练，或重写数据集dataset部分即可。

**Comment by jxz2021114** [comment]
谢谢解答！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yatengLG"<notifications@github.com&gt;; 
发送时间: 2020年8月6日(星期四) 下午3:25
收件人: "yatengLG/SSD-Pytorch"<SSD-Pytorch@noreply.github.com&gt;; 
抄送: "漙"<1808319533@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yatengLG/SSD-Pytorch] 求数据集来源 (#6)





 
你去下载Pascal VOC 数据集即可。
 如果需要训练自己的数据，把数据转成VOC格式(网上有很多文章和代码)即可使用原代码训练，或重写数据集dataset部分即可。
