### ISSUE TITLE
gpu利用率特别低

### ISSUE THREAD

**Issue by mingzhanliao** [yatengLG/SSD-Pytorch#7]
我在测试训练时，发现gpu利用率特别低，似乎没有用到gpu,只用了显存

**Comment by yatengLG** [comment]
怎么个情况，详细说说？

**Comment by mingzhanliao** [comment]
是windows10GPU利用率显示的问题

**Comment by yatengLG** [comment]
1. 如果你显存占满了，就说明你batch_size已经最大了。如果没占满，你可以稍微调大你的batch_size。
2. 如果是在显存占满，但是GPU还有空闲，就是说明数据处理部分速度较慢，你可以适当调大num_workers 调大，用更多线程去处理数据。
![gnome-shell-screenshot-61LIR0](https://user-images.githubusercontent.com/31759824/93279949-19cdef80-f7fb-11ea-9c6e-887af3ef2684.png)

**Comment by mingzhanliao** [comment]
好的，感谢！
