### ISSUE TITLE
训练无法达到作者给的模型精度

### ISSUE THREAD

**Issue by aisaterm** [yatengLG/SSD-Pytorch#9]
你好，我用voc2007和voc2012分别训练，得到的训练mAP的数值与作者提供的相差太大，请问原因出现在哪，谢谢

**Comment by yatengLG** [comment]
您好，很不好意思给你造成了困扰。
所提供的模型，并没有与config相对应。
config配置只是提供了一个基础模板，并表明了各参数说明。你可以很方便的在此基础上进行修改，并应用到你的项目中去。

如果你这是需要在voc上达到所提供的精度，你可以在voc2007以及2012的trainval上一起进行训练，并将批次或训练轮数提高（项目中是双卡训练），并在训练完成后，对模型在单卡上进行微调。
